gcp mdxc updates
massdriver-cloud/application-templates pull request #24
Opened 2022-08-29 01:50 UTC by WillBeebe

- [x] cloud run terraform, app, etc
- [ ] template-ize
- [ ] cloud functions

2022-08-30 03:33 UTC, xpositivityx approved these changes

2022-08-30 03:45 UTC, coryodaniel requested changes

2022-08-30 03:45 UTC, coryodaniel commented on gcp-cloud-function/src/main.tf
> +  source               = "./module"
We should move this to `terraform-modules` the goal is to get the `main.tf` as succinct as possible.

I would name it `massdriver-application-gcp-cloud-function` and call `application` inside of it so they just have one module to pass vars into.

2022-08-30 03:45 UTC, coryodaniel commented on gcp-cloud-function/src/module/storage.tf
> +data "archive_file" "appfiles" {
Why do we have these nodejs files in here? We should be working with container repositories only.

2022-08-30 03:45 UTC, coryodaniel commented on gcp-cloud-run/src/main.tf
> +  source          = "github.com/massdriver-cloud/terraform-modules//gcp-application-cloud-run"
If it’s specific to a Massdriver app let’s make sure we name these consistently. massdriver-application-

2022-08-30 17:45 UTC, WillBeebe commented on gcp-cloud-run/src/main.tf
> +  source          = "github.com/massdriver-cloud/terraform-modules//gcp-application-cloud-run"
```suggestion
  source          = "github.com/massdriver-cloud/terraform-modules//massdriver-application-gcp-cloud-run"
```

2022-09-09 03:24 UTC, WillBeebe commented
@coryodaniel I got all the modules merged, updated this and used it to locally create a new app. It's ready for another review.

2022-09-09 15:33 UTC, coryodaniel requested changes

2022-09-09 15:33 UTC, coryodaniel commented on gcp-cloud-run/massdriver.yaml
> +          # If you need to allow an end-user developer to select the container repo, you can use our drop down widget documented here: https://docs.massdriver.cloud/bundles/custom-widgets-and-fields
```suggestion
          # You'll generally want to hard code your container repository in your bundle code, 
          # but it can be helpful to show it in your schema as well.
```

2022-09-09 15:33 UTC, coryodaniel commented on gcp-cloud-run/massdriver.yaml
> +          # If you need to allow an end-user developer to select the container repo, you can use our drop down widget documented here: https://docs.massdriver.cloud/bundles/custom-widgets-and-fields
Pulled container repos from UI, its been buggy. We added docs for creating the repo via CLI for now. A more interesting fix is coming shortly.

2022-09-09 15:33 UTC, coryodaniel commented on gcp-cloud-run/massdriver.yaml
> +  #     cloud: "gcp"
```suggestion
```

2022-09-09 15:33 UTC, coryodaniel commented on gcp-cloud-run/massdriver.yaml
> +      cloud: gcp
```suggestion
```

2022-09-09 15:33 UTC, coryodaniel commented on gcp-cloud-run/src/main.tf
> +  zone               = var.endpoint.enabled ? var.endpoint.zone.name : ""
Why are the fallbacks empty strings? Can we make this an optional field on the module and let it handle any weird terraform null-ish type internals.

2022-09-09 15:41 UTC, WillBeebe commented on gcp-cloud-run/src/main.tf
> +  zone               = var.endpoint.enabled ? var.endpoint.zone.name : ""
Fair point, I'll make the changes to the module to handle nulls. 👍

2022-09-09 17:59 UTC, coryodaniel commented on gcp-cloud-run/src/main.tf
> +  zone               = var.endpoint.enabled ? var.endpoint.zone.name : ""
FFTM afterwards.

Feelfree to merge if thats a new acronym, idk.

2022-09-12 00:01 UTC, WillBeebe commented on gcp-cloud-run/src/main.tf
> +  zone               = var.endpoint.enabled ? var.endpoint.zone.name : ""
Module PR here: https://github.com/massdriver-cloud/terraform-modules/pull/40

I won't be able to merge until you change your review from changes requested to approved. 🙏

2022-09-12 17:17 UTC, coryodaniel approved these changes

2022-09-12 18:10 UTC, merged