Make connection strongly typed.
massdriver-cloud/application-templates pull request #89
Opened 2023-03-12 03:43 UTC by akasprzok

The only question is - artifact-definition or artifact_definition?

Corresponding changes need to be made to CLI before we roll this out.

2023-03-13 15:45 UTC, coryodaniel commented
Key accessed names should be _ otherwise YMMV in some programming languages

2023-03-13 16:23 UTC, coryodaniel requested changes, later dismissed

2023-03-13 16:23 UTC, coryodaniel commented on aws-ecs-service/massdriver.yaml
> +      $ref: {{conn.artifact-definition}}
Key accessed names should be _ otherwise YMMV in some programming languages

2023-03-15 17:55 UTC, xpositivityx approved these changes

2023-03-15 17:58 UTC, merged